-- Seed Products Data

INSERT INTO public.products (
  slug, name, description, long_description, price, original_price, weight, image, images, category, type, origin, harvest, taste, tags, in_stock, featured, rating, reviews_count
) VALUES
(
  'shan-tuyet-co-thu',
  'Shan Tuyết Cổ Thụ',
  'Hương thơm cốm non, vị ngọt hậu sâu lắng từ Suối Giàng.',
  'Trà Shan Tuyết Cổ Thụ được thu hái từ những cây chè hàng trăm năm tuổi trên đỉnh Suối Giàng, Yên Bái. Búp chè to, phủ lớp lông tuyết trắng mịn, khi pha cho nước màu vàng mật ong, hương thơm cốm non nồng nàn và vị ngọt hậu sâu lắng. Đây là tặng phẩm vô giá của núi rừng Tây Bắc.',
  450000,
  NULL,
  '100g',
  '🌿',
  ARRAY['🌿', '🍵', '🍃', '🏔️'],
  'tea',
  'green',
  'Suối Giàng, Yên Bái',
  'Vụ Xuân 2024',
  'Chát dịu, ngọt hậu, hương cốm',
  ARRAY['Best Seller', 'Organic'],
  true,
  true,
  4.8,
  124
),
(
  'bach-tra-tien',
  'Bạch Trà Tiên',
  'Những búp trà phủ lông tuyết trắng, hương hoa cỏ tinh tế.',
  'Bạch Trà Tiên là loại trà quý hiếm, chỉ hái một tôm (búp non nhất). Quá trình chế biến tối giản giúp giữ nguyên vẹn hương vị tự nhiên của đất trời. Trà có màu nước trắng ngà, hương thơm hoa cỏ tinh tế, vị thanh mát, giàu chất chống oxy hóa.',
  850000,
  NULL,
  '100g',
  '🍵',
  ARRAY['🍵', '❄️', '🌱'],
  'tea',
  'white',
  'Tây Côn Lĩnh, Hà Giang',
  'Vụ Xuân 2024',
  'Thanh mát, hương hoa, ngọt nhẹ',
  ARRAY['Premium', 'Limited'],
  true,
  true,
  4.9,
  89
),
(
  'hong-tra-co-thu',
  'Hồng Trà Cổ Thụ',
  'Lên men tự nhiên, hương mật ong và trái cây chín.',
  'Hồng Trà Cổ Thụ 84tea được lên men 100% từ lá chè Shan Tuyết cổ thụ. Nước trà màu đỏ hổ phách đẹp mắt, hương thơm nồng nàn của mật ong rừng và trái cây chín. Vị trà đậm đà, không chát, để lại dư vị ngọt ngào khó quên.',
  380000,
  NULL,
  '100g',
  '🍂',
  ARRAY['🍂', '🍯', '🥃'],
  'tea',
  'black',
  'Mộc Châu, Sơn La',
  'Vụ Hè 2024',
  'Đậm đà, hương mật ong, trái cây',
  ARRAY['New', 'Warm'],
  true,
  true,
  4.7,
  56
),
(
  'hoang-tra-di-san',
  'Hoàng Trà Di Sản',
  'Công thức chế biến gia truyền, vị êm dịu độc đáo.',
  'Hoàng Trà (Trà Vàng) là dòng trà quý tộc, được chế biến qua quy trình ''m悶 hoàng'' đặc biệt. Trà có hương thơm thảo mộc nhẹ nhàng, nước vàng óng ả, vị êm dịu, không gắt, rất tốt cho tiêu hóa.',
  550000,
  NULL,
  '100g',
  '✨',
  ARRAY['✨', '👑', '🌼'],
  'tea',
  'herbal',
  'Thái Nguyên',
  'Vụ Thu 2023',
  'Êm dịu, thảo mộc, thanh khiết',
  ARRAY['Limited', 'Heritage'],
  true,
  true,
  4.6,
  42
),
(
  'o-long-cao-son',
  'Ô Long Cao Sơn',
  'Viên tròn đều, hương sữa và hoa lan quyến rũ.',
  'Ô Long Cao Sơn được trồng ở độ cao trên 1000m. Lá trà được vo thành viên tròn, khi pha nở ra nguyên búp. Hương thơm đặc trưng của sữa và hoa lan, vị ngọt thanh, chát nhẹ, nước xanh vàng trong vắt.',
  650000,
  NULL,
  '100g',
  '🏞️',
  ARRAY['🏞️', '🌫️', '🍃'],
  'tea',
  'oolong',
  'Lâm Đồng',
  'Vụ Đông 2023',
  'Hương sữa, hoa lan, ngọt thanh',
  ARRAY['Popular'],
  true,
  false,
  4.7,
  98
),
(
  'bo-am-chen-tu-sa',
  'Bộ Ấm Chén Tử Sa',
  'Chế tác thủ công từ đất tử sa Nghi Hưng cao cấp.',
  'Bộ ấm chén Tử Sa được các nghệ nhân chế tác thủ công tỉ mỉ. Chất đất tử sa giữ nhiệt tốt, càng dùng càng bóng đẹp, giúp tôn vinh hương vị trà ngon nhất. Bộ sản phẩm gồm 1 ấm, 6 chén và 1 tống chuyên trà.',
  2500000,
  3000000,
  '1 bộ',
  '🏺',
  ARRAY['🏺', '🫖', '🎁'],
  'teaware',
  NULL,
  'Nghi Hưng',
  NULL,
  NULL,
  ARRAY['Handmade', 'Luxury'],
  true,
  false,
  5.0,
  15
),
(
  'hop-qua-tet-sum-vay',
  'Hộp Quà Tết Sum Vầy',
  'Kết hợp 3 loại trà thượng hạng, thiết kế sang trọng.',
  'Hộp quà Tết ''Sum Vầy'' mang thông điệp đoàn viên, hạnh phúc. Bên trong là 3 hũ trà thượng hạng: Shan Tuyết, Hồng Trà và Ô Long. Thiết kế hộp sơn mài sang trọng, thích hợp làm quà biếu đối tác, người thân dịp lễ Tết.',
  1250000,
  NULL,
  '1 set',
  '🎁',
  ARRAY['🎁', '🧧', '✨'],
  'gift',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['Gift Set', 'Seasonal'],
  true,
  false,
  4.8,
  34
),
(
  'tra-pho-nhi-song',
  'Trà Phổ Nhĩ Sống 2015',
  'Bánh trà nén chặt, càng để lâu càng giá trị.',
  'Bánh trà Phổ Nhĩ sống được sản xuất năm 2015 từ nguyên liệu Shan Tuyết cổ thụ. Trà có vị chát mạnh ban đầu nhưng ngọt hậu kéo dài, hương thơm của nắng và gió núi rừng. Thích hợp để thưởng thức ngay hoặc lưu trữ lâu dài.',
  1500000,
  NULL,
  '357g',
  '💿',
  ARRAY['💿', '🕰️', '🏔️'],
  'tea',
  'black',
  'Hà Giang',
  '2015',
  'Mạnh mẽ, ngọt hậu, hương gỗ',
  ARRAY['Aged', 'Collector'],
  true,
  false,
  4.9,
  28
);
